event_inherited();
idlespr = spr_knight_idle;
stunfallspr = spr_forknight_stun;
walkspr = spr_forknight_walk;
grabbedspr = spr_forknight_grabbed;
scaredspr = spr_forknight_scared;
turnspr = spr_forknight_turn;
landspr = spr_forknight_walk;
deadspr = spr_forknight_dead;
spr_palette = palette_forknight;