draw_set_font(global.smallfont)
draw_set_halign(fa_left)
draw_sprite(spr_editor_modes_placeholder, buttons_mode[1], 0, 0)
draw_text(20, 100, "CATEGORY " + selected_category)
draw_text(20, 130, "PLACING " + string_upper(object_get_name(selected_obj)))
draw_text(20, 160, "X " + string(selected_obj_x))
draw_text(20, 190, "Y " + string(selected_obj_y))
draw_text(20, 220, "WIDTH " + string(selected_obj_w))
draw_text(20, 250, "HEIGHT " + string(selected_obj_h))
draw_text(20, 280, "ROTATION  " + string(selected_obj_r))
draw_text(20, 310, string(buttons_mode))
draw_sprite(spr_cursor, 0, cursor_x, cursor_y)