draw_set_font(global.smallfont)
draw_set_halign(fa_left)
draw_text(20, 20, "CATEGORY " + selected_category)
draw_text(20, 50, "PLACING " + string_upper(object_get_name(selected_obj)))
draw_text(20, 80, "X " + string(selected_obj_x))
draw_text(20, 110, "Y " + string(selected_obj_y))
draw_text(20, 140, "WIDTH " + string(selected_obj_w))
draw_text(20, 170, "HEIGHT " + string(selected_obj_h))
draw_text(20, 200, "ROTATION  " + string(selected_obj_r))
draw_sprite(spr_cursor, 0, cursor_x, cursor_y)