event_inherited();
landspr = spr_minijohn_charge;
idlespr = spr_minijohn_stun;
fallspr = spr_minijohn_charge;
stunfallspr = spr_minijohn_stun;
walkspr = spr_minijohn_charge;
turnspr = spr_minijohn_charge;
recoveryspr = spr_minijohn_charge;
grabbedspr = spr_minijohn_stun;
scaredspr = spr_minijohn_stun;
deadspr = spr_minijohn_dead;
ragespr = spr_minijohn_punch;
spr_palette = spr_minijohn_palette;