optionselected = 0;
ini_open("optionData.ini");
global.defaultlapmusic = ini_read_real("Settings", "defaultlap", 0);
global.mulap10 = ini_read_real("Settings", "mu_lap10", 0);
global.mulap5 = ini_read_real("Settings", "mu_lap5", 0);
global.mulap2 = ini_read_real("Settings", "mu_lap2", 0);
global.muescape = ini_read_real("Settings", "mu_escape", 0);
ini_close();
optionsaved_defaultlap = global.defaultlapmusic;
optionsaved_mu_lap10 = global.mulap10;
optionsaved_mu_lap5 = global.mulap5;
optionsaved_mu_lap2 = global.mulap2;
optionsaved_mu_escape = global.muescape;
subtitle = "GO BACK TO MAIN SCREEN";
CursorY = -999;
ScrollY = 0;
depth = -100;
selecting = -1;
obj_Options_Mod.CursorY = -999;
obj_Options_Main.CursorX = 150;
canmove = false;
alarm[0] = 1;
