if instance_exists(obj_palettechangerscrollbar)
	instance_destroy(obj_palettechangerscrollbar);
with obj_player
{
	array_delete(my_palettes, array_length(my_palettes), 10)
	array_delete(my_palettes, (array_length(my_palettes) - 1), 10)
	array_delete(my_palettes, (array_length(my_palettes) - 2), 10)
	ini_open("Custom/Pizzelle_1_palettes.ini")
	global.custompal_1_col_0 = (65536 * ini_read_real("PizzelleColors0", "Blue", 0) + (256 * ini_read_real("PizzelleColors0", "Green", 0) + ini_read_real("PizzelleColors0", "Red", 0)))
	global.custompal_1_col_1 = (65536 * ini_read_real("PizzelleColors1", "Blue", 0) + (256 * ini_read_real("PizzelleColors1", "Green", 0) + ini_read_real("PizzelleColors1", "Red", 0)))
	global.custompal_1_col_2 = (65536 * ini_read_real("PizzelleColors2", "Blue", 0) + (256 * ini_read_real("PizzelleColors2", "Green", 0) + ini_read_real("PizzelleColors2", "Red", 0)))
	global.custompal_1_col_3 = (65536 * ini_read_real("PizzelleColors3", "Blue", 0) + (256 * ini_read_real("PizzelleColors3", "Green", 0) + ini_read_real("PizzelleColors3", "Red", 0)))
	global.custompal_1_col_4 = (65536 * ini_read_real("PizzelleColors4", "Blue", 0) + (256 * ini_read_real("PizzelleColors4", "Green", 0) + ini_read_real("PizzelleColors4", "Red", 0)))
	global.custompal_1_col_5 = (65536 * ini_read_real("PizzelleColors5", "Blue", 0) + (256 * ini_read_real("PizzelleColors5", "Green", 0) + ini_read_real("PizzelleColors5", "Red", 0)))
	global.custompal_1_col_6 = (65536 * ini_read_real("PizzelleColors6", "Blue", 0) + (256 * ini_read_real("PizzelleColors6", "Green", 0) + ini_read_real("PizzelleColors6", "Red", 0)))
	global.custompal_1_col_7 = (65536 * ini_read_real("PizzelleColors7", "Blue", 0) + (256 * ini_read_real("PizzelleColors7", "Green", 0) + ini_read_real("PizzelleColors7", "Red", 0)))
	global.custompal_1_col_8 = (65536 * ini_read_real("PizzelleColors8", "Blue", 0) + (256 * ini_read_real("PizzelleColors8", "Green", 0) + ini_read_real("PizzelleColors8", "Red", 0)))
	global.custompal_1_col_9 = (65536 * ini_read_real("PizzelleColors9", "Blue", 0) + (256 * ini_read_real("PizzelleColors9", "Green", 0) + ini_read_real("PizzelleColors9", "Red", 0)))
	global.custompal_1_col_10 = (65536 * ini_read_real("PizzelleColors10", "Blue", 0) + (256 * ini_read_real("PizzelleColors10", "Green", 0) + ini_read_real("PizzelleColors10", "Red", 0)))
	ini_close()
	ini_open("Custom/Pizzelle_2_palettes.ini")
	global.custompal_2_col_0 = (65536 * ini_read_real("PizzelleColors0", "Blue", 0) + (256 * ini_read_real("PizzelleColors0", "Green", 0) + ini_read_real("PizzelleColors0", "Red", 0)))
	global.custompal_2_col_1 = (65536 * ini_read_real("PizzelleColors1", "Blue", 0) + (256 * ini_read_real("PizzelleColors1", "Green", 0) + ini_read_real("PizzelleColors1", "Red", 0)))
	global.custompal_2_col_2 = (65536 * ini_read_real("PizzelleColors2", "Blue", 0) + (256 * ini_read_real("PizzelleColors2", "Green", 0) + ini_read_real("PizzelleColors2", "Red", 0)))
	global.custompal_2_col_3 = (65536 * ini_read_real("PizzelleColors3", "Blue", 0) + (256 * ini_read_real("PizzelleColors3", "Green", 0) + ini_read_real("PizzelleColors3", "Red", 0)))
	global.custompal_2_col_4 = (65536 * ini_read_real("PizzelleColors4", "Blue", 0) + (256 * ini_read_real("PizzelleColors4", "Green", 0) + ini_read_real("PizzelleColors4", "Red", 0)))
	global.custompal_2_col_5 = (65536 * ini_read_real("PizzelleColors5", "Blue", 0) + (256 * ini_read_real("PizzelleColors5", "Green", 0) + ini_read_real("PizzelleColors5", "Red", 0)))
	global.custompal_2_col_6 = (65536 * ini_read_real("PizzelleColors6", "Blue", 0) + (256 * ini_read_real("PizzelleColors6", "Green", 0) + ini_read_real("PizzelleColors6", "Red", 0)))
	global.custompal_2_col_7 = (65536 * ini_read_real("PizzelleColors7", "Blue", 0) + (256 * ini_read_real("PizzelleColors7", "Green", 0) + ini_read_real("PizzelleColors7", "Red", 0)))
	global.custompal_2_col_8 = (65536 * ini_read_real("PizzelleColors8", "Blue", 0) + (256 * ini_read_real("PizzelleColors8", "Green", 0) + ini_read_real("PizzelleColors8", "Red", 0)))
	global.custompal_2_col_9 = (65536 * ini_read_real("PizzelleColors9", "Blue", 0) + (256 * ini_read_real("PizzelleColors9", "Green", 0) + ini_read_real("PizzelleColors9", "Red", 0)))
	global.custompal_2_col_10 = (65536 * ini_read_real("PizzelleColors10", "Blue", 0) + (256 * ini_read_real("PizzelleColors10", "Green", 0) + ini_read_real("PizzelleColors10", "Red", 0)))
	ini_close()
	ini_open("Custom/Pizzelle_3_palettes.ini")
	global.custompal_3_col_0 = (65536 * ini_read_real("PizzelleColors0", "Blue", 0) + (256 * ini_read_real("PizzelleColors0", "Green", 0) + ini_read_real("PizzelleColors0", "Red", 0)))
	global.custompal_3_col_1 = (65536 * ini_read_real("PizzelleColors1", "Blue", 0) + (256 * ini_read_real("PizzelleColors1", "Green", 0) + ini_read_real("PizzelleColors1", "Red", 0)))
	global.custompal_3_col_2 = (65536 * ini_read_real("PizzelleColors2", "Blue", 0) + (256 * ini_read_real("PizzelleColors2", "Green", 0) + ini_read_real("PizzelleColors2", "Red", 0)))
	global.custompal_3_col_3 = (65536 * ini_read_real("PizzelleColors3", "Blue", 0) + (256 * ini_read_real("PizzelleColors3", "Green", 0) + ini_read_real("PizzelleColors3", "Red", 0)))
	global.custompal_3_col_4 = (65536 * ini_read_real("PizzelleColors4", "Blue", 0) + (256 * ini_read_real("PizzelleColors4", "Green", 0) + ini_read_real("PizzelleColors4", "Red", 0)))
	global.custompal_3_col_5 = (65536 * ini_read_real("PizzelleColors5", "Blue", 0) + (256 * ini_read_real("PizzelleColors5", "Green", 0) + ini_read_real("PizzelleColors5", "Red", 0)))
	global.custompal_3_col_6 = (65536 * ini_read_real("PizzelleColors6", "Blue", 0) + (256 * ini_read_real("PizzelleColors6", "Green", 0) + ini_read_real("PizzelleColors6", "Red", 0)))
	global.custompal_3_col_7 = (65536 * ini_read_real("PizzelleColors7", "Blue", 0) + (256 * ini_read_real("PizzelleColors7", "Green", 0) + ini_read_real("PizzelleColors7", "Red", 0)))
	global.custompal_3_col_8 = (65536 * ini_read_real("PizzelleColors8", "Blue", 0) + (256 * ini_read_real("PizzelleColors8", "Green", 0) + ini_read_real("PizzelleColors8", "Red", 0)))
	global.custompal_3_col_9 = (65536 * ini_read_real("PizzelleColors9", "Blue", 0) + (256 * ini_read_real("PizzelleColors9", "Green", 0) + ini_read_real("PizzelleColors9", "Red", 0)))
	global.custompal_3_col_10 = (65536 * ini_read_real("PizzelleColors10", "Blue", 0) + (256 * ini_read_real("PizzelleColors10", "Green", 0) + ini_read_real("PizzelleColors10", "Red", 0)))
	ini_close()
	new_palette("Custom 1", 0, global.custompal_1_col_1, global.custompal_1_col_10, global.custompal_1_col_3, global.custompal_1_col_2, global.custompal_1_col_4, global.custompal_1_col_5, global.custompal_1_col_0, global.custompal_1_col_2);
	new_palette("Custom 2", 0, global.custompal_2_col_1, global.custompal_2_col_10, global.custompal_2_col_3, global.custompal_2_col_2, global.custompal_2_col_4, global.custompal_2_col_5, global.custompal_2_col_0, global.custompal_2_col_2);
	new_palette("Custom 3", 0, global.custompal_3_col_1, global.custompal_3_col_10, global.custompal_3_col_3, global.custompal_3_col_2, global.custompal_3_col_4, global.custompal_3_col_5, global.custompal_3_col_0, global.custompal_3_col_2);
}