optionselected = 0;
ini_open("optionData.ini");
global.newscorefont = ini_read_real("Settings", "newscorefont", 0);
global.newplayeranim = ini_read_real("Settings", "newplayeranim", 0);
global.erankstack = ini_read_real("Settings", "erankstack", 0);
global.slopeangle = ini_read_real("Settings", "slopeangle", 1);
global.machsfx = ini_read_real("Settings", "machsfx", 1);
global.eggplantcombo = ini_read_real("Settings", "eggplantcombo", 0);
global.oldhud = ini_read_real("Settings", "oldhud", 0);
ini_close();
optionsaved_newscorefont = global.newscorefont;
optionsaved_newplayeranim = global.newplayeranim;
optionsaved_erankstack = global.erankstack;
optionsaved_slopeangle = global.slopeangle;
optionsaved_machsfx = global.machsfx;
optionsaved_eggplantcombo = global.eggplantcombo;
optionsaved_oldhud = global.oldhud;
subtitle = "GO BACK TO MAIN SCREEN";
CursorY = -999;
ScrollY = 0;
depth = -100;
selecting = -1;
obj_Options_Mod.CursorY = -999;
obj_Options_Main.CursorX = 150;
canmove = false;
alarm[0] = 1;
