draw_set_font(global.font);
draw_set_halign(1);
draw_option(150, 30 + ScrollY, "BACK", optionselected == 0);
draw_option(480, 100 + ScrollY, "HEATMETER", optionselected == 1);
draw_option(280, 150 + ScrollY, "ON", optionsaved_heatmeter);
draw_option(680, 150 + ScrollY, "OFF", !optionsaved_heatmeter);
draw_option(480, 200 + ScrollY, "LEVEL DESIGN", optionselected == 2);
draw_option(180, 250 + ScrollY, "DEFAULT", optionsaved_newlvldesign == 0);
draw_option(480, 250 + ScrollY, "NEW", optionsaved_newlvldesign == 1);
draw_option(780, 250 + ScrollY, "OLD", optionsaved_newlvldesign == 2);
draw_option(780, 250 + ScrollY, "CUSTOM", optionsaved_newlvldesign == 3);
draw_option(480, 300 + ScrollY, "LAPPING MODE", optionselected == 3);
draw_option(180, 350 + ScrollY, "DEFAULT", optionsaved_inflapping == 0);
draw_option(480, 350 + ScrollY, "INFINITE", optionsaved_inflapping == 1);
draw_option(780, 350 + ScrollY, "CHALLENGE", optionsaved_inflapping == 2);
draw_option(480, 400 + ScrollY, "ENABLE JERALD", optionselected == 4);
draw_option(280, 450 + ScrollY, "ON", optionsaved_enablejerald);
draw_option(680, 450 + ScrollY, "OFF", !optionsaved_enablejerald);
draw_option(480, 500 + ScrollY, "WEAKER CONEBALL", optionselected == 5);
draw_option(280, 550 + ScrollY, "ON", optionsaved_coneballparry);
draw_option(680, 550 + ScrollY, "OFF", !optionsaved_coneballparry);
draw_set_font(global.smallfont);
draw_set_halign(1);
var _string_width = string_width(subtitle) + 32;
if (subtitle != "")
	draw_sprite_ext(spr_optionSubtitle, 0, 480, 521, _string_width / 32, 1, 0, c_white, 1);
draw_text(480, 512, subtitle);
